#!/usr/bin/env python

# Run this before you deploy it on replicate
import os
import sys
import torch
from diffusers import StableDiffusionImg2ImgPipeline

# append project directory to path so predict.py can be imported
sys.path.append('.')
from predict import MODEL_CACHE

# Make cache folders
if not os.path.exists(MODEL_CACHE):
    os.makedirs(MODEL_CACHE)
    
url = "https://huggingface.co/invisiblecat/Uber_Realistic_Porn_Merge_V1.3_inpainting/blob/main/urpm-inpainting.safetensors"
pipe = StableDiffusionImg2ImgPipeline.from_single_file(
    url,
    torch_dtype=torch.float16
)

pipe.save_pretrained(MODEL_CACHE)
